{
    "tests": [
        {
            "output": {
                "passfail": "failed"
            },
            "traceback": "Traceback (most recent call last):\n  File \"/home/vmuser_vgpnjktw/verify_student_output.py\", line 32, in handler\n    queue.put((None, testcase(obj)))\n  File \"/home/vmuser_vgpnjktw/CVResult.py\", line 29, in func_wrapper\n    ans = func(self)\n  File \"run.py\", line 337, in test_HaarFeature_evaluate\n    self.assertTrue(correct, message)\nAssertionError: Wrong score returned while using feature type (1, 2).\n",
            "description": "Testing HaarFeature.evaluate (25 points)"
        },
        {
            "output": {
                "passfail": "passed"
            },
            "traceback": "",
            "description": "Testing average face (10 points)"
        },
        {
            "output": {
                "passfail": "passed"
            },
            "traceback": "",
            "description": "Testing pca eigenvalues (15 points)"
        },
        {
            "output": {
                "passfail": "passed"
            },
            "traceback": "",
            "description": "Testing split_dataset (10 points)"
        },
        {
            "output": {
                "passfail": "passed"
            },
            "traceback": "",
            "description": "Testing Boosting.evaluate (10 points)"
        },
        {
            "output": {
                "passfail": "passed"
            },
            "traceback": "",
            "description": "Testing Boosting.predict (10 points)"
        },
        {
            "output": {
                "passfail": "passed"
            },
            "traceback": "",
            "description": "Testing convert_images_to_integral_images (10 points)"
        },
        {
            "output": {
                "passfail": "passed"
            },
            "traceback": "",
            "description": "Testing HaarFeature.preview (10 points)"
        }
    ],
    "unauthorized_lib_calls": []
}